<%@ Import Namespace="System.Xml" %>
<%@ Import Namespace="System.Data" %>
<%@ Import Namespace="System.Data.SqlClient" %>
<%@ Page Language="VB" Title="Export Result - Orders Blind Online" ContentType="text/xml" Debug="true" %>

<script runat="server">
    Dim myConn As String = ConfigurationManager.ConnectionStrings("DefaultConnection").ConnectionString

    Dim publigCfg As New PublicConfig

    Protected Sub Page_Load(sender As Object, e As EventArgs)
        Dim fromDate As String = DateTime.Parse(Request.QueryString("fromdate")).ToString("yyyy-MM-dd")
        Dim toDate As String = DateTime.Parse(Request.QueryString("todate")).AddDays(1).ToString("yyyy-MM-dd")
        Dim status As String = Request.QueryString("status").ToString()
        Dim type As String = Request.QueryString("type").ToString()
        Dim action As String = Request.QueryString("action").ToString()

        Dim statusString = ""
        Dim dateString As String = " AND SubmittedDate >= '" + fromDate + "' AND SubmittedDate <= '" + toDate + "'"

        If status = "all" Then
            statusString = " AND Status <> ''"
            dateString = " AND CreatedDate >= '" + fromDate + "' AND CreatedDate <= '" + toDate + "'"
        End If
        If status = "draft" Then
            statusString = " AND (Status = 'Draft' OR Status = 'Quoted')"
            dateString = " AND CreatedDate >= '" + fromDate + "' AND CreatedDate <= '" + toDate + "'"
        End If
        If status = "new" Then
            statusString = " AND Status = 'New Order'"
        End If
        If status = "production" Then
            statusString = " AND Status = 'In Production'"
        End If
        If status = "hold" Then
            statusString = " AND Status = 'Hold'"
        End If
        If status = "completed" Then
            statusString = " AND Status = 'Shipped Out'"
        End If
        If status = "canceled" Then
            statusString = " AND Status = 'Canceled'"
        End If

        If type = "headersp" Then
            Dim myQuery As String = String.Format("SELECT * FROM OrderHeaders WHERE Active=1 {0} {1} ORDER BY Id ASC", statusString, dateString)

            Dim myData As DataSet = publigCfg.GetListData(myQuery)
            Call DataHeaderSP(myData)

            If action = "download" Then
                Call UpdateAfterDownloadSOE(dateString)
            End If
        End If

        If type = "detailsp" Then
            Dim myQuery As String = String.Format("SELECT view_details.* FROM view_details INNER JOIN OrderHeaders ON view_details.HeaderId = OrderHeaders.Id INNER JOIN Stores ON OrderHeaders.StoreId = Stores.Id WHERE view_details.Active = 1 AND OrderHeaders.Active = 1 {0} {1}", statusString, dateString)

            Dim myData As DataSet = publigCfg.GetListData(myQuery)
            Call DataDetailSP(myData)
        End If

        If type = "headersg" Then
            Dim myQuery As String = String.Format("SELECT OrderHeaders.*, Memberships.UserName AS UserName FROM OrderHeaders INNER JOIN Memberships ON OrderHeaders.UserId = Memberships.UserId INNER JOIN Stores ON OrderHeaders.StoreId = Stores.Id WHERE OrderHeaders.Active = 1 AND Stores.Company = 'SG' {0} {1} ORDER BY OrderHeaders.Id ASC", statusString, dateString)

            Dim myData As DataSet = publigCfg.GetListData(myQuery)
            Call DataHeaderSG(myData)

            If action = "download" Then
                Call UpdateAfterDownloadBOE(dateString)
            End If
        End If

        If type = "detailsg" Then
            Dim myQuery As String = String.Format("SELECT OrderDetails_Global.* FROM OrderDetails_Global INNER JOIN OrderHeaders ON OrderDetails_Global.HeaderId = OrderHeaders.Id INNER JOIN Stores ON OrderHeaders.StoreId = Stores.Id WHERE OrderDetails_Global.Active = 1 AND OrderHeaders.Active = 1 AND Stores.Company = 'SG' {0} {1}", statusString, dateString)

            Dim myData As DataSet = publigCfg.GetListData(myQuery)
            Call DataDetailSG(myData)
        End If
    End Sub

    Private Sub UpdateAfterDownloadSOE(paramDate As String)
        Using thisConn As New SqlConnection(myConn)
            thisConn.Open()
            Dim myQuery As String = String.Format("UPDATE OrderHeaders INNER JOIN Stores ON OrderHeaders.StoreId = Stores.Id SET Status='In Production' FROM OrderHeaders WHERE Active=1 AND Status = 'New Order' AND Stores.Company = 'SP' {0}", paramDate)
            Using myCmd As New SqlCommand(myQuery, thisConn)
                myCmd.CommandType = CommandType.Text
                myCmd.ExecuteNonQuery()
            End Using
            thisConn.Close()
        End Using
    End Sub

    Private Sub UpdateAfterDownloadBOE(paramDate As String)
        Using thisConn As New SqlConnection(myConn)
            thisConn.Open()
            Dim myQuery As String = String.Format("UPDATE OrderHeaders INNER JOIN Stores ON OrderHeaders.StoreId = Stores.Id SET Status='In Production' FROM OrderHeaders WHERE Active=1 AND Status = 'New Order' AND Stores.Company = 'SG' {0}", paramDate)
            Using myCmd As New SqlCommand(myQuery, thisConn)
                myCmd.CommandType = CommandType.Text
                myCmd.ExecuteNonQuery()
            End Using
            thisConn.Close()
        End Using
    End Sub

    Private Sub DataHeaderSP(myData As DataSet)
        Dim writer As New XmlTextWriter(Response.OutputStream, Encoding.ASCII)
        writer.WriteStartDocument()
        writer.WriteStartElement("Orders")

        For i As Integer = 0 To myData.Tables(0).Rows.Count - 1
            writer.WriteStartElement("OrderHeader")
            writer.WriteAttributeString("OrdID", myData.Tables(0).Rows(i).Item("Id").ToString())
            writer.WriteAttributeString("StoreOrderNo", myData.Tables(0).Rows(i).Item("OrderNo").ToString())
            writer.WriteAttributeString("StoreCustomer", myData.Tables(0).Rows(i).Item("OrderCust").ToString())
            writer.WriteAttributeString("CreatedDate", myData.Tables(0).Rows(i).Item("CreatedDate").ToString())
            writer.WriteAttributeString("SubmittedDate", myData.Tables(0).Rows(i).Item("SubmittedDate").ToString())
            writer.WriteAttributeString("CanceledDate", myData.Tables(0).Rows(i).Item("CanceledDate").ToString())
            writer.WriteAttributeString("CompletedDate", myData.Tables(0).Rows(i).Item("CompletedDate").ToString())
            writer.WriteAttributeString("UserLogin", myData.Tables(0).Rows(i).Item("UserId").ToString())
            writer.WriteAttributeString("DebtorCode", myData.Tables(0).Rows(i).Item("StoreId").ToString())
            writer.WriteAttributeString("Delivery", myData.Tables(0).Rows(i).Item("Delivery").ToString())
            writer.WriteAttributeString("Status", myData.Tables(0).Rows(i).Item("Status").ToString())
            writer.WriteAttributeString("StatusDescription", myData.Tables(0).Rows(i).Item("StatusDescription").ToString())
            writer.WriteAttributeString("Active", myData.Tables(0).Rows(i).Item("Active").ToString())
            writer.WriteEndElement()
        Next
        writer.WriteEndElement()
        writer.WriteEndDocument()
        writer.Close()
    End Sub

    Private Sub DataDetailSP(myData As DataSet)
        Dim writer As New XmlTextWriter(Response.OutputStream, Encoding.ASCII)
        writer.WriteStartDocument()
        writer.WriteStartElement("Orders")

        For i As Integer = 0 To myData.Tables(0).Rows.Count - 1
            writer.WriteStartElement("OrderDetails")

            writer.WriteAttributeString("OrddID", myData.Tables(0).Rows(i).Item("Id").ToString())
            writer.WriteAttributeString("FKOrdID", myData.Tables(0).Rows(i).Item("HeaderId").ToString())
            writer.WriteAttributeString("KitId", myData.Tables(0).Rows(i).Item("KitId").ToString())
            writer.WriteAttributeString("DesignName", myData.Tables(0).Rows(i).Item("DesignName").ToString())
            writer.WriteAttributeString("BlindName", myData.Tables(0).Rows(i).Item("BlindName").ToString())
            writer.WriteAttributeString("ColourType", myData.Tables(0).Rows(i).Item("ColourType").ToString())
            writer.WriteAttributeString("Qty", myData.Tables(0).Rows(i).Item("Qty").ToString())
            writer.WriteAttributeString("Mounting", myData.Tables(0).Rows(i).Item("Mounting").ToString())
            writer.WriteAttributeString("Width", myData.Tables(0).Rows(i).Item("Width").ToString())
            writer.WriteAttributeString("WidthB", myData.Tables(0).Rows(i).Item("WidthB").ToString())
            writer.WriteAttributeString("Width2C", "")
            writer.WriteAttributeString("WidthMiddle", myData.Tables(0).Rows(i).Item("WidthMiddle").ToString())
            writer.WriteAttributeString("Drop", myData.Tables(0).Rows(i).Item("Drop").ToString())
            writer.WriteAttributeString("DropB", myData.Tables(0).Rows(i).Item("DropB").ToString())
            writer.WriteAttributeString("Drop3C", "")
            writer.WriteAttributeString("DropMiddle", myData.Tables(0).Rows(i).Item("DropMiddle").ToString())
            writer.WriteAttributeString("DropRight", myData.Tables(0).Rows(i).Item("DropRight").ToString())
            writer.WriteAttributeString("ControlPosition", myData.Tables(0).Rows(i).Item("ControlPosition").ToString())
            writer.WriteAttributeString("TilterPosition", myData.Tables(0).Rows(i).Item("TilterPosition").ToString())
            writer.WriteAttributeString("ValancePosition", "")
            writer.WriteAttributeString("ValanceReturnSize", "")
            writer.WriteAttributeString("Notes", myData.Tables(0).Rows(i).Item("Notes").ToString())
            writer.WriteAttributeString("Location", myData.Tables(0).Rows(i).Item("Location").ToString())
            writer.WriteAttributeString("WidthBottom", myData.Tables(0).Rows(i).Item("WidthBottom").ToString())
            writer.WriteAttributeString("LayoutCode", "")
            writer.WriteAttributeString("TrackColour", myData.Tables(0).Rows(i).Item("TrackColour").ToString())
            writer.WriteAttributeString("BottomRailType3a", "")
            writer.WriteAttributeString("Panel", "")
            writer.WriteAttributeString("Supply", "")
            writer.WriteAttributeString("FabricID_DoubleBracket", "")
            writer.WriteAttributeString("FabricID_LinkSys", "")
            writer.WriteAttributeString("FabricID_LinkSysIdp", "")
            writer.WriteAttributeString("RomanMechanismType", "")
            writer.WriteAttributeString("RomanValanceOption", "")
            writer.WriteAttributeString("RomanHR", "")
            writer.WriteAttributeString("Production", "")
            writer.WriteAttributeString("BottomRailColour", "")
            writer.WriteAttributeString("BottomRailType", "")
            writer.WriteAttributeString("BottomColour2a", "")
            writer.WriteAttributeString("BottomType2a", "")
            writer.WriteAttributeString("BottomColour2b", "")
            writer.WriteAttributeString("BottomType2b", "")
            writer.WriteAttributeString("BottomColour2c", "")
            writer.WriteAttributeString("Roll", "")
            writer.WriteAttributeString("ChainType", "")
            writer.WriteAttributeString("Chain2a", "")
            writer.WriteAttributeString("Chain2c", myData.Tables(0).Rows(i).Item("ChainColour").ToString())
            writer.WriteAttributeString("RolChainLength2c", "")
            writer.WriteAttributeString("RollerBracketColour", "")
            writer.WriteAttributeString("RollDirection", "")
            writer.WriteAttributeString("Roll2a", "")
            writer.WriteAttributeString("PullCordLength", "")
            writer.WriteAttributeString("RomanChainLength", "")
            writer.WriteAttributeString("RomanChainOption", "")
            writer.WriteAttributeString("IDChain_DoubleBracket", "")
            writer.WriteAttributeString("IDChain_LinkSysIdp", "")
            writer.WriteAttributeString("IDBottomRail", "")
            writer.WriteAttributeString("IDBottomRail_DoubleBracket", "")
            writer.WriteAttributeString("IDBottomRail_LinkSys", "")
            writer.WriteAttributeString("IDBottomRail_LinkSysIdp", "")
            writer.WriteAttributeString("WandLength", "")
            writer.WriteAttributeString("IDBottomRail_LinkSysIdp_3rd", "")
            writer.WriteAttributeString("IDBottomRail_LinkSys_3rd", "")
            writer.WriteAttributeString("IDChain_LSIdp3rd", "")
            writer.WriteAttributeString("FabricID_LSIdp3rd", "")
            writer.WriteAttributeString("FabricID_LS3rd", "")
            writer.WriteAttributeString("Width_LS3rd", "")
            writer.WriteAttributeString("FabricType_LS3b", "")
            writer.WriteAttributeString("BottomType_LS3b", "")
            writer.WriteAttributeString("BottomColour_LS3b", "")
            writer.WriteAttributeString("Width_LSIdp3rd", "")
            writer.WriteAttributeString("Drop_LSIdp3rd", "")
            writer.WriteAttributeString("FabricType_LSIdp3rd", "")
            writer.WriteAttributeString("Chain_LSIdp3rd", "")
            writer.WriteAttributeString("ChainLength_LSIdp3rd", "")
            writer.WriteAttributeString("BottomType_LSIdp3rd", "")
            writer.WriteAttributeString("BottomColour_LSIdp3rd", "")
            writer.WriteAttributeString("NumOfBlind", "")
            writer.WriteAttributeString("ControlType", "")
            writer.WriteAttributeString("ControlOperation", "")
            writer.WriteAttributeString("FabricInsert", "")
            writer.WriteAttributeString("BottomJoin", "")
            writer.WriteAttributeString("Vertical_HeadrailColour", "")
            writer.WriteAttributeString("Vertical_WandCordColour", "")
            writer.WriteAttributeString("StackOption", "")
            writer.WriteAttributeString("ControlLength", "")
            writer.WriteAttributeString("ControlLength2", "")
            writer.WriteAttributeString("AwningType", "")
            writer.WriteAttributeString("ValanceType", "")
            writer.WriteAttributeString("VerHRColour", "")
            writer.WriteAttributeString("FlatArm", "")
            writer.WriteAttributeString("SoeKitId", myData.Tables(0).Rows(i).Item("SoeKitId").ToString())
            writer.WriteAttributeString("HookType", "")
            writer.WriteAttributeString("HookQty", "")
            writer.WriteAttributeString("PelmetLayout", "")
            writer.WriteAttributeString("IDHK2", "")
            writer.WriteAttributeString("IDHK3", "")
            writer.WriteAttributeString("IDHK4", "")
            writer.WriteAttributeString("FlatBottomOp", "")
            writer.WriteAttributeString("Extbracket", "")
            writer.WriteAttributeString("FlatBottomOp2a", "")
            writer.WriteAttributeString("FlatBottomOp2b", "")
            writer.WriteAttributeString("FlatBottomOp3b", "")
            writer.WriteAttributeString("FlatBottomOp2c", "")
            writer.WriteAttributeString("FlatBottomOp3c", "")
            writer.WriteAttributeString("FlatBottomOpDB3b", "")
            writer.WriteAttributeString("FlatBottomOp4b", "")
            writer.WriteAttributeString("FlatBottomOpDB3c", "")
            writer.WriteAttributeString("FlatBottomOp4c", "")
            writer.WriteAttributeString("ControlPosition_LSDouble3rd", "")
            writer.WriteAttributeString("FabricID_LSDouble3rd", "")
            writer.WriteAttributeString("FabricID_LSDouble4th", "")
            writer.WriteAttributeString("FabricID_LSIdpDouble3rd", "")
            writer.WriteAttributeString("FabricID_LSIdpDouble4th", "")
            writer.WriteAttributeString("IDBottomRail_LSDouble3rd", "")
            writer.WriteAttributeString("IDBottomRail_LSDouble4th", "")
            writer.WriteAttributeString("IDBottomRail_LSIdpDouble3rd", "")
            writer.WriteAttributeString("IDBottomRail_LSIdpDouble4th", "")
            writer.WriteAttributeString("IDChain_LSDouble3rd", "")
            writer.WriteAttributeString("IDChain_LSIdpDouble3rd", "")
            writer.WriteAttributeString("IDChain_LSIdpDouble4th", "")
            writer.WriteAttributeString("Chain_LSDouble3rd", "")
            writer.WriteAttributeString("Chain_LSIdpDouble3rd", "")
            writer.WriteAttributeString("Additional", "")
            writer.WriteAttributeString("Additional2", "")
            writer.WriteAttributeString("Additional3", "")
            writer.WriteAttributeString("SubType", "")
            writer.WriteAttributeString("Roll_LSDouble3rd", "")
            writer.WriteAttributeString("ControlColour", "")
            writer.WriteAttributeString("IDpriceadd", "")
            writer.WriteAttributeString("IDpriceadd2", "")
            writer.WriteAttributeString("IDpriceadd3", "")
            writer.WriteAttributeString("IDpriceadd4", "")
            writer.WriteAttributeString("IDpriceadd5", "")
            writer.WriteAttributeString("IDpriceadd6", "")
            writer.WriteAttributeString("IDpriceadd7", "")
            writer.WriteAttributeString("IDpriceadd8", "")
            writer.WriteAttributeString("FabricTypedb4", "")
            writer.WriteAttributeString("BottomTypedb4", "")
            writer.WriteAttributeString("FlatBottomdb4", "")
            writer.WriteAttributeString("BottomColourdb4", "")
            writer.WriteAttributeString("Chaindb4", "")
            writer.WriteAttributeString("chainst4", "")
            writer.WriteAttributeString("ChainLengthdb4", "")
            writer.WriteAttributeString("FabricTypedb5", "")
            writer.WriteAttributeString("BottomTypedb5", "")
            writer.WriteAttributeString("FlatBottomop5", "")
            writer.WriteAttributeString("BottomColourdb5", "")
            writer.WriteAttributeString("FabricTypedb6", "")
            writer.WriteAttributeString("BottomTypedb6", "")
            writer.WriteAttributeString("FlatBottomop6", "")
            writer.WriteAttributeString("BottomColourdb6", "")
            writer.WriteAttributeString("Chaindb6", "")
            writer.WriteAttributeString("chainst6", "")
            writer.WriteAttributeString("ChainLengthdb6", "")
            writer.WriteAttributeString("FabricTypedb7", "")
            writer.WriteAttributeString("BottomTypedb7", "")
            writer.WriteAttributeString("FlatBottomop7", "")
            writer.WriteAttributeString("BottomColourdb7", "")
            writer.WriteAttributeString("Chaindb7", "")
            writer.WriteAttributeString("chainst7", "")
            writer.WriteAttributeString("ChainLengthdb7", "")
            writer.WriteAttributeString("IDpriceadd9", "")
            writer.WriteAttributeString("IDpriceadd10", "")
            writer.WriteAttributeString("IDpriceadd11", "")
            writer.WriteAttributeString("IDpriceadd12", "")
            writer.WriteAttributeString("IDpriceadd13", "")
            writer.WriteAttributeString("IDpriceadd14", "")
            writer.WriteAttributeString("IDpriceadd15", "")
            writer.WriteAttributeString("IDpriceadd16", "")
            writer.WriteAttributeString("IDHK5", "")
            writer.WriteAttributeString("IDHK6", "")
            writer.WriteAttributeString("IDHK7", "")
            writer.WriteAttributeString("IDHK8", "")
            writer.WriteAttributeString("FabricID", myData.Tables(0).Rows(i).Item("FabricId").ToString())
            writer.WriteAttributeString("FabricID5", "")
            writer.WriteAttributeString("FabricID6", "")
            writer.WriteAttributeString("FabricID7", "")
            writer.WriteAttributeString("FabricID8", "")
            writer.WriteAttributeString("IDChainDBL", "")
            writer.WriteAttributeString("IDChainDBR", "")
            writer.WriteAttributeString("IDBottomRail5", "")
            writer.WriteAttributeString("IDBottomRail6", "")
            writer.WriteAttributeString("IDBottomRail7", "")
            writer.WriteAttributeString("IDBottomRail8", "")
            writer.WriteAttributeString("SideHem", "")
            writer.WriteAttributeString("ChainID", myData.Tables(0).Rows(i).Item("ChainId").ToString())
            writer.WriteAttributeString("Battens", "")
            writer.WriteAttributeString("bottomcolour3c", "")
            writer.WriteAttributeString("RomanChainColour", "")
            writer.WriteAttributeString("Instruction", "")
            writer.WriteAttributeString("ControlPositionDB3b", "")
            writer.WriteAttributeString("BrType", "")
            writer.WriteAttributeString("fabrictype3c", "")
            writer.WriteAttributeString("VerWandColour", "")
            writer.WriteAttributeString("latch_base", "")
            writer.WriteAttributeString("width_min", "")
            writer.WriteAttributeString("width3b", "")
            writer.WriteAttributeString("width3c", "")
            writer.WriteAttributeString("mesh_type", "")
            writer.WriteAttributeString("LadderType", "")
            writer.WriteAttributeString("track_top_double", "")
            writer.WriteAttributeString("RollDB3b", "")
            writer.WriteAttributeString("MotorType", "")
            writer.WriteAttributeString("ValanceSize", "")
            writer.WriteAttributeString("frame_type", "")
            writer.WriteAttributeString("width_bottom", "")
            writer.WriteAttributeString("bottomtype3c", "")
            writer.WriteAttributeString("FabricType2c", "")
            writer.WriteAttributeString("OtherQty", "")
            writer.WriteAttributeString("width_middle", "")
            writer.WriteAttributeString("Bracket", "")
            writer.WriteAttributeString("frame_colour", "")
            writer.WriteAttributeString("handle_position", "")
            writer.WriteAttributeString("handle_measure", "")
            writer.WriteAttributeString("handle_height", "")
            writer.WriteAttributeString("midrail_position", "")
            writer.WriteAttributeString("pet_door_type", "")
            writer.WriteAttributeString("pet_door_position", "")
            writer.WriteAttributeString("LockType", "")
            writer.WriteAttributeString("bugseal_alumunium", "")
            writer.WriteAttributeString("door_closer_colour", "")
            writer.WriteAttributeString("jamb_adaptor_colour", "")
            writer.WriteAttributeString("jamb_adaptor_toplength", "")
            writer.WriteAttributeString("jamb_adaptor_sidelength", "")
            writer.WriteAttributeString("angle_first", "")
            writer.WriteAttributeString("angle_length_first", "")
            writer.WriteAttributeString("angle_second", "")
            writer.WriteAttributeString("angle_length_second", "")
            writer.WriteAttributeString("track_j", "")
            writer.WriteAttributeString("track_w", "")
            writer.WriteAttributeString("track_u", "")
            writer.WriteAttributeString("track_p", "")
            writer.WriteAttributeString("ChainLengthDB3b", "")
            writer.WriteAttributeString("ChainLengthDB3c", "")
            writer.WriteAttributeString("UChannelLength", "")
            writer.WriteAttributeString("beading_stop_bead_colour", "")
            writer.WriteAttributeString("beading_stop_bead", "")
            writer.WriteAttributeString("RollerChainLength", "")
            writer.WriteAttributeString("interlock_length", "")
            writer.WriteAttributeString("chainlength3c", "")
            writer.WriteAttributeString("winder_strip_length", "")
            writer.WriteAttributeString("fabrictype3b", "")
            writer.WriteAttributeString("plunger_pin_metal", "")
            writer.WriteAttributeString("plunger_pin_plain", "")
            writer.WriteAttributeString("trun_button_flush", "")
            writer.WriteAttributeString("trun_button_extended", "")
            writer.WriteAttributeString("port_hole", "")
            writer.WriteAttributeString("Cranklen", "")
           writer.WriteEndElement()
        Next
        writer.WriteEndElement()
        writer.WriteEndDocument()
        writer.Close()
    End Sub

    Private Sub DataHeaderSG(myData As DataSet)
        Dim writer As New XmlTextWriter(Response.OutputStream, Encoding.ASCII)
        writer.WriteStartDocument()
        writer.WriteStartElement("Orders")

        For i As Integer = 0 To myData.Tables(0).Rows.Count - 1
            writer.WriteStartElement("OrderHeader")

            writer.WriteEndElement()
        Next

        writer.WriteEndElement()
        writer.WriteEndDocument()
        writer.Close()
    End Sub

    Private Sub DataDetailSG(myData As DataSet)
        Dim writer As New XmlTextWriter(Response.OutputStream, Encoding.ASCII)
        writer.WriteStartDocument()
        writer.WriteStartElement("Orders")

        For i As Integer = 0 To myData.Tables(0).Rows.Count - 1
            writer.WriteStartElement("OrderDetails")
            writer.WriteAttributeString("Id", myData.Tables(0).Rows(i).Item("Id").ToString())
            writer.WriteAttributeString("HeaderId", myData.Tables(0).Rows(i).Item("HeaderId").ToString())
            writer.WriteAttributeString("KitId", myData.Tables(0).Rows(i).Item("KitId").ToString())
            writer.WriteAttributeString("KitIdB", myData.Tables(0).Rows(i).Item("KitIdB").ToString())
            writer.WriteAttributeString("KitIdC", myData.Tables(0).Rows(i).Item("KitIdC").ToString())
            writer.WriteAttributeString("KitIdD", myData.Tables(0).Rows(i).Item("KitIdD").ToString())
            writer.WriteAttributeString("FabricId", myData.Tables(0).Rows(i).Item("FabricId").ToString())
            writer.WriteAttributeString("FabricIdB", myData.Tables(0).Rows(i).Item("FabricIdB").ToString())
            writer.WriteAttributeString("FabricIdC", myData.Tables(0).Rows(i).Item("FabricIdC").ToString())
            writer.WriteAttributeString("FabricIdD", myData.Tables(0).Rows(i).Item("FabricIdD").ToString())
            writer.WriteAttributeString("ChainId", myData.Tables(0).Rows(i).Item("ChainId").ToString())
            writer.WriteAttributeString("ChainIdB", myData.Tables(0).Rows(i).Item("ChainIdB").ToString())
            writer.WriteAttributeString("ChainIdC", myData.Tables(0).Rows(i).Item("ChainIdC").ToString())
            writer.WriteAttributeString("ChainIdD", myData.Tables(0).Rows(i).Item("ChainIdD").ToString())
            writer.WriteAttributeString("BottomRailId", myData.Tables(0).Rows(i).Item("BottomRailId").ToString())
            writer.WriteAttributeString("BottomRailIdB", myData.Tables(0).Rows(i).Item("BottomRailIdB").ToString())
            writer.WriteAttributeString("BottomRailIdC", myData.Tables(0).Rows(i).Item("BottomRailIdC").ToString())
            writer.WriteAttributeString("BottomRailIdD", myData.Tables(0).Rows(i).Item("BottomRailIdD").ToString())
            writer.WriteAttributeString("Qty", myData.Tables(0).Rows(i).Item("Qty").ToString())
            writer.WriteAttributeString("SlatSize", myData.Tables(0).Rows(i).Item("SlatSize").ToString())
            writer.WriteAttributeString("SlatQty", myData.Tables(0).Rows(i).Item("SlatQty").ToString())
            writer.WriteAttributeString("Location", myData.Tables(0).Rows(i).Item("Location").ToString())
            writer.WriteAttributeString("Mounting", myData.Tables(0).Rows(i).Item("Mounting").ToString())
            writer.WriteAttributeString("Colour", myData.Tables(0).Rows(i).Item("Colour").ToString())
            writer.WriteAttributeString("Width", myData.Tables(0).Rows(i).Item("Width").ToString())
            writer.WriteAttributeString("WidthB", myData.Tables(0).Rows(i).Item("WidthB").ToString())
            writer.WriteAttributeString("WidthC", myData.Tables(0).Rows(i).Item("WidthC").ToString())
            writer.WriteAttributeString("WidthD", myData.Tables(0).Rows(i).Item("WidthD").ToString())
            writer.WriteAttributeString("WidthMiddle", myData.Tables(0).Rows(i).Item("WidthMiddle").ToString())
            writer.WriteAttributeString("WidthBottom", myData.Tables(0).Rows(i).Item("WidthBottom").ToString())
            writer.WriteAttributeString("Drop", myData.Tables(0).Rows(i).Item("Drop").ToString())
            writer.WriteAttributeString("DropB", myData.Tables(0).Rows(i).Item("DropB").ToString())
            writer.WriteAttributeString("DropC", myData.Tables(0).Rows(i).Item("DropC").ToString())
            writer.WriteAttributeString("DropD", myData.Tables(0).Rows(i).Item("DropD").ToString())
            writer.WriteAttributeString("DropMiddle", myData.Tables(0).Rows(i).Item("DropMiddle").ToString())
            writer.WriteAttributeString("DropRight", myData.Tables(0).Rows(i).Item("DropRight").ToString())
            writer.WriteAttributeString("StackPosition", myData.Tables(0).Rows(i).Item("StackPosition").ToString())
            writer.WriteAttributeString("TilterPosition", myData.Tables(0).Rows(i).Item("TilterPosition").ToString())
            writer.WriteAttributeString("RollDirection", myData.Tables(0).Rows(i).Item("RollDirection").ToString())
            writer.WriteAttributeString("RollDirectionB", myData.Tables(0).Rows(i).Item("RollDirectionB").ToString())
            writer.WriteAttributeString("RollDirectionC", myData.Tables(0).Rows(i).Item("RollDirectionC").ToString())
            writer.WriteAttributeString("RollDirectionD", myData.Tables(0).Rows(i).Item("RollDirectionD").ToString())
            writer.WriteAttributeString("ControlType", myData.Tables(0).Rows(i).Item("ControlType").ToString())
            writer.WriteAttributeString("ControlPosition", myData.Tables(0).Rows(i).Item("ControlPosition").ToString())
            writer.WriteAttributeString("ControlPositionB", myData.Tables(0).Rows(i).Item("ControlPositionB").ToString())
            writer.WriteAttributeString("ControlPositionC", myData.Tables(0).Rows(i).Item("ControlPositionC").ToString())
            writer.WriteAttributeString("ControlPositionD", myData.Tables(0).Rows(i).Item("ControlPositionD").ToString())
            writer.WriteAttributeString("ControlColour", myData.Tables(0).Rows(i).Item("ControlColour").ToString())
            writer.WriteAttributeString("ControlLength", myData.Tables(0).Rows(i).Item("ControlLength").ToString())
            writer.WriteAttributeString("ChainColour", myData.Tables(0).Rows(i).Item("ChainColour").ToString())
            writer.WriteAttributeString("ChainColourB", myData.Tables(0).Rows(i).Item("ChainColourB").ToString())
            writer.WriteAttributeString("ChainColourC", myData.Tables(0).Rows(i).Item("ChainColourC").ToString())
            writer.WriteAttributeString("ChainColourD", myData.Tables(0).Rows(i).Item("ChainColourD").ToString())
            writer.WriteAttributeString("ChainLength", myData.Tables(0).Rows(i).Item("ChainLength").ToString())
            writer.WriteAttributeString("ChainLengthB", myData.Tables(0).Rows(i).Item("ChainLengthB").ToString())
            writer.WriteAttributeString("ChainLengthC", myData.Tables(0).Rows(i).Item("ChainLengthC").ToString())
            writer.WriteAttributeString("ChainLengthD", myData.Tables(0).Rows(i).Item("ChainLengthD").ToString())
            writer.WriteAttributeString("MotorType", myData.Tables(0).Rows(i).Item("MotorType").ToString())
            writer.WriteAttributeString("MotorStyle", myData.Tables(0).Rows(i).Item("MotorStyle").ToString())
            writer.WriteAttributeString("MotorRemote", myData.Tables(0).Rows(i).Item("MotorRemote").ToString())
            writer.WriteAttributeString("MotorRequired", myData.Tables(0).Rows(i).Item("MotorRequired").ToString())
            writer.WriteAttributeString("MotorCharger", myData.Tables(0).Rows(i).Item("MotorCharger").ToString())
            writer.WriteAttributeString("Connector", myData.Tables(0).Rows(i).Item("Connector").ToString())
            writer.WriteAttributeString("AdditionalMotor", myData.Tables(0).Rows(i).Item("AdditionalMotor").ToString())
            writer.WriteAttributeString("CableExitPoint", myData.Tables(0).Rows(i).Item("CableExitPoint").ToString())
            writer.WriteAttributeString("TrackType", myData.Tables(0).Rows(i).Item("TrackType").ToString())
            writer.WriteAttributeString("TrackColour", myData.Tables(0).Rows(i).Item("TrackColour").ToString())
            writer.WriteAttributeString("TrackLength", myData.Tables(0).Rows(i).Item("TrackLength").ToString())
            writer.WriteAttributeString("WandColour", myData.Tables(0).Rows(i).Item("WandColour").ToString())
            writer.WriteAttributeString("WandLength", myData.Tables(0).Rows(i).Item("WandLength").ToString())
            writer.WriteAttributeString("Accessory", myData.Tables(0).Rows(i).Item("Accessory").ToString())
            writer.WriteAttributeString("TubeType", myData.Tables(0).Rows(i).Item("TubeType").ToString())
            writer.WriteAttributeString("TubeSize", myData.Tables(0).Rows(i).Item("TubeSize").ToString())
            writer.WriteAttributeString("Trim", myData.Tables(0).Rows(i).Item("Trim").ToString())
            writer.WriteAttributeString("TrimB", myData.Tables(0).Rows(i).Item("TrimB").ToString())
            writer.WriteAttributeString("TrimC", myData.Tables(0).Rows(i).Item("TrimC").ToString())
            writer.WriteAttributeString("TrimD", myData.Tables(0).Rows(i).Item("TrimD").ToString())
            writer.WriteAttributeString("BracketType", myData.Tables(0).Rows(i).Item("BracketType").ToString())
            writer.WriteAttributeString("BracketColour", myData.Tables(0).Rows(i).Item("BracketColour").ToString())
            writer.WriteAttributeString("BracketCover", myData.Tables(0).Rows(i).Item("BracketCover").ToString())
            writer.WriteAttributeString("BracketExtension", myData.Tables(0).Rows(i).Item("BracketExtension").ToString())
            writer.WriteAttributeString("FlatType", myData.Tables(0).Rows(i).Item("FlatType").ToString())
            writer.WriteAttributeString("ChildSafe", myData.Tables(0).Rows(i).Item("ChildSafe").ToString())
            writer.WriteAttributeString("BottomHoldDown", myData.Tables(0).Rows(i).Item("BottomHoldDown").ToString())
            writer.WriteAttributeString("HangerType", myData.Tables(0).Rows(i).Item("HangerType").ToString())
            writer.WriteAttributeString("PelmetType", myData.Tables(0).Rows(i).Item("PelmetType").ToString())
            writer.WriteAttributeString("PelmetWidth", myData.Tables(0).Rows(i).Item("PelmetWidth").ToString())
            writer.WriteAttributeString("PelmetSize", myData.Tables(0).Rows(i).Item("PelmetSize").ToString())
            writer.WriteAttributeString("PelmetReturn", myData.Tables(0).Rows(i).Item("PelmetReturn").ToString())
            writer.WriteAttributeString("PelmetReturn2", myData.Tables(0).Rows(i).Item("PelmetReturn2").ToString())
            writer.WriteAttributeString("LHSWidth_Top", myData.Tables(0).Rows(i).Item("LHSWidth_Top").ToString())
            writer.WriteAttributeString("LHSHeight_Top", myData.Tables(0).Rows(i).Item("LHSHeight_Top").ToString())
            writer.WriteAttributeString("RHSWidth_Top", myData.Tables(0).Rows(i).Item("RHSWidth_Top").ToString())
            writer.WriteAttributeString("RHSHeight_Top", myData.Tables(0).Rows(i).Item("RHSHeight_Top").ToString())
            writer.WriteAttributeString("LHSWidth_Bottom", myData.Tables(0).Rows(i).Item("LHSWidth_Bottom").ToString())
            writer.WriteAttributeString("LHSHeight_Bottom", myData.Tables(0).Rows(i).Item("LHSHeight_Bottom").ToString())
            writer.WriteAttributeString("RHSWidth_Bottom", myData.Tables(0).Rows(i).Item("RHSWidth_Bottom").ToString())
            writer.WriteAttributeString("RHSHeight_Bottom", myData.Tables(0).Rows(i).Item("RHSHeight_Bottom").ToString())
            writer.WriteAttributeString("BlindSize", myData.Tables(0).Rows(i).Item("BlindSize").ToString())
            writer.WriteAttributeString("Sloper", myData.Tables(0).Rows(i).Item("Sloper").ToString())
            writer.WriteAttributeString("InsertInTrack", myData.Tables(0).Rows(i).Item("InsertInTrack").ToString())
            writer.WriteAttributeString("SQM", myData.Tables(0).Rows(i).Item("SQM").ToString())
            writer.WriteAttributeString("SQMB", myData.Tables(0).Rows(i).Item("SQMB").ToString())
            writer.WriteAttributeString("SQMC", myData.Tables(0).Rows(i).Item("SQMC").ToString())
            writer.WriteAttributeString("SQMD", myData.Tables(0).Rows(i).Item("SQMD").ToString())
            writer.WriteAttributeString("Notes", myData.Tables(0).Rows(i).Item("Notes").ToString())
            writer.WriteAttributeString("Cost", myData.Tables(0).Rows(i).Item("Cost").ToString())
            writer.WriteAttributeString("Charge", myData.Tables(0).Rows(i).Item("Charge").ToString())
            writer.WriteAttributeString("Active", myData.Tables(0).Rows(i).Item("Active").ToString())

            writer.WriteEndElement()
        Next
        writer.WriteEndElement()
        writer.WriteEndDocument()
        writer.Close()
    End Sub
</script>