CREATE TABLE JobSheets (
    Id INT PRIMARY KEY IDENTITY(1,1),
    JobId INT,
    PageOf INT,
    AmountOfPage INT,
    JoNumber NVARCHAR(100),
    HeaderId INT,
    DesignName NVARCHAR(100),
    BlindName NVARCHAR(100),
		AmountBlind INT,
    StoreName NVARCHAR(100),
    OrderNo NVARCHAR(100),
    OrderCust NVARCHAR(100),
    ZoneId NVARCHAR(100),
    UserName NVARCHAR(100),
    OrderCreated DATE,
    JobCreated DATE DEFAULT GETDATE(),
    ShipDate NVARCHAR(100),

	----------------|| buat menjadi 1-6, contoh : BlindNo1, BlindNo2,... BlindNo6 sampi filed terakhir || ------------------------------------
    Line1 NVARCHAR(50),
    Line2 NVARCHAR(50),
    Line3 NVARCHAR(50),
    Line4 NVARCHAR(50),
    Line5 NVARCHAR(50),
    Line6 NVARCHAR(50),

    Qty1 INT,
    Qty2 INT,
    Qty3 INT,
    Qty4 INT,
    Qty5 INT,
    Qty6 INT,

    Location1 NVARCHAR(100),
    Location2 NVARCHAR(100),
    Location3 NVARCHAR(100),
    Location4 NVARCHAR(100),
    Location5 NVARCHAR(100),
    Location6 NVARCHAR(100),

    Mounting1 NVARCHAR(100),
    Mounting2 NVARCHAR(100),
    Mounting3 NVARCHAR(100),
    Mounting4 NVARCHAR(100),
    Mounting5 NVARCHAR(100),
    Mounting6 NVARCHAR(100),
    
    Width1 INT,
    Width2 INT,
    Width3 INT,
    Width4 INT,
    Width5 INT,
    Width6 INT,
    
    WidthB1 INT,
    WidthB2 INT,
    WidthB3 INT,
    WidthB4 INT,
    WidthB5 INT,
    WidthB6 INT,

    WidthMiddle1 INT,
    WidthMiddle2 INT,
    WidthMiddle3 INT,
    WidthMiddle4 INT,
    WidthMiddle5 INT,
    WidthMiddle6 INT,

    WidthBottom1 INT,
    WidthBottom2 INT,
    WidthBottom3 INT,
    WidthBottom4 INT,
    WidthBottom5 INT,
    WidthBottom6 INT,

    Drop1 INT,
    Drop2 INT,
    Drop3 INT,
    Drop4 INT,
    Drop5 INT,
    Drop6 INT,

    DropB1 INT,
    DropB2 INT,
    DropB3 INT,
    DropB4 INT,
    DropB5 INT,
    DropB6 INT,

    DropMiddle1 INT,
    DropMiddle2 INT,
    DropMiddle3 INT,
    DropMiddle4 INT,
    DropMiddle5 INT,
    DropMiddle6 INT,

    DropRight1 INT,
    DropRight2 INT,
    DropRight3 INT,
    DropRight4 INT,
    DropRight5 INT,
    DropRight6 INT,

    SemiInsideMount1 NVARCHAR(100),
    SemiInsideMount2 NVARCHAR(100),
    SemiInsideMount3 NVARCHAR(100),
    SemiInsideMount4 NVARCHAR(100),
    SemiInsideMount5 NVARCHAR(100),
    SemiInsideMount6 NVARCHAR(100),

    LouvreSize1 NVARCHAR(100),
    LouvreSize2 NVARCHAR(100),
    LouvreSize3 NVARCHAR(100),
    LouvreSize4 NVARCHAR(100),
    LouvreSize5 NVARCHAR(100),
    LouvreSize6 NVARCHAR(100),

    LouvrePosition1 NVARCHAR(100),
    LouvrePosition2 NVARCHAR(100),
    LouvrePosition3 NVARCHAR(100),
    LouvrePosition4 NVARCHAR(100),
    LouvrePosition5 NVARCHAR(100),
    LouvrePosition6 NVARCHAR(100),

    HingeColour1 NVARCHAR(100),
    HingeColour2 NVARCHAR(100),
    HingeColour3 NVARCHAR(100),
    HingeColour4 NVARCHAR(100),
    HingeColour5 NVARCHAR(100),
    HingeColour6 NVARCHAR(100),

    MidrailHeight1 INT,
    MidrailHeight2 INT,
    MidrailHeight3 INT,
    MidrailHeight4 INT,
    MidrailHeight5 INT,
    MidrailHeight6 INT,

    MidrailCritical1 NVARCHAR(100),
    MidrailCritical2 NVARCHAR(100),
    MidrailCritical3 NVARCHAR(100),
    MidrailCritical4 NVARCHAR(100),
    MidrailCritical5 NVARCHAR(100),
    MidrailCritical6 NVARCHAR(100),
    
    Layout1 NVARCHAR(100),
    Layout2 NVARCHAR(100),
    Layout3 NVARCHAR(100),
    Layout4 NVARCHAR(100),
    Layout5 NVARCHAR(100),
    Layout6 NVARCHAR(100),

    LayoutSpecial1 NVARCHAR(100),
    LayoutSpecial2 NVARCHAR(100),
    LayoutSpecial3 NVARCHAR(100),
    LayoutSpecial4 NVARCHAR(100),
    LayoutSpecial5 NVARCHAR(100),
    LayoutSpecial6 NVARCHAR(100),

    CustomHeaderLength1 INT,
    CustomHeaderLength2 INT,
    CustomHeaderLength3 INT,
    CustomHeaderLength4 INT,
    CustomHeaderLength5 INT,
    CustomHeaderLength6 INT,

    FrameType1 NVARCHAR(100),
    FrameType2 NVARCHAR(100),
    FrameType3 NVARCHAR(100),
    FrameType4 NVARCHAR(100),
    FrameType5 NVARCHAR(100),
    FrameType6 NVARCHAR(100),

    FrameLeft1 NVARCHAR(100),
    FrameLeft2 NVARCHAR(100),
    FrameLeft3 NVARCHAR(100),
    FrameLeft4 NVARCHAR(100),
    FrameLeft5 NVARCHAR(100),
    FrameLeft6 NVARCHAR(100),

    FrameRight1 NVARCHAR(100),
    FrameRight2 NVARCHAR(100),
    FrameRight3 NVARCHAR(100),
    FrameRight4 NVARCHAR(100),
    FrameRight5 NVARCHAR(100),
    FrameRight6 NVARCHAR(100),

    FrameTop1 NVARCHAR(100),
    FrameTop2 NVARCHAR(100),
    FrameTop3 NVARCHAR(100),
    FrameTop4 NVARCHAR(100),
    FrameTop5 NVARCHAR(100),
    FrameTop6 NVARCHAR(100),

    FrameBottom1 NVARCHAR(100),
    FrameBottom2 NVARCHAR(100),
    FrameBottom3 NVARCHAR(100),
    FrameBottom4 NVARCHAR(100),
    FrameBottom5 NVARCHAR(100),
    FrameBottom6 NVARCHAR(100),

    BottomTrackType1 NVARCHAR(100),
    BottomTrackType2 NVARCHAR(100),
    BottomTrackType3 NVARCHAR(100),
    BottomTrackType4 NVARCHAR(100),
    BottomTrackType5 NVARCHAR(100),
    BottomTrackType6 NVARCHAR(100),

    BottomTrackRecess1 NVARCHAR(100),
    BottomTrackRecess2 NVARCHAR(100),
    BottomTrackRecess3 NVARCHAR(100),
    BottomTrackRecess4 NVARCHAR(100),
    BottomTrackRecess5 NVARCHAR(100),
    BottomTrackRecess6 NVARCHAR(100),

    Buildout1 NVARCHAR(100),
    Buildout2 NVARCHAR(100),
    Buildout3 NVARCHAR(100),
    Buildout4 NVARCHAR(100),
    Buildout5 NVARCHAR(100),
    Buildout6 NVARCHAR(100),

    BuildoutPosition1 NVARCHAR(100),
    BuildoutPosition2 NVARCHAR(100),
    BuildoutPosition3 NVARCHAR(100),
    BuildoutPosition4 NVARCHAR(100),
    BuildoutPosition5 NVARCHAR(100),
    BuildoutPosition6 NVARCHAR(100),

    PanelQty1 INT,
    PanelQty2 INT,
    PanelQty3 INT,
    PanelQty4 INT,
    PanelQty5 INT,
    PanelQty6 INT,

    TrackQty1 INT,
    TrackQty2 INT,
    TrackQty3 INT,
    TrackQty4 INT,
    TrackQty5 INT,
    TrackQty6 INT,

    PanelSize1 NVARCHAR(100),
    PanelSize2 NVARCHAR(100),
    PanelSize3 NVARCHAR(100),
    PanelSize4 NVARCHAR(100),
    PanelSize5 NVARCHAR(100),
    PanelSize6 NVARCHAR(100),

    NumOfPanel1 INT,
    NumOfPanel2 INT,
    NumOfPanel3 INT,
    NumOfPanel4 INT,
    NumOfPanel5 INT,
    NumOfPanel6 INT,

    HingeQtyPerPanel1 INT,
    HingeQtyPerPanel2 INT,
    HingeQtyPerPanel3 INT,
    HingeQtyPerPanel4 INT,
    HingeQtyPerPanel5 INT,
    HingeQtyPerPanel6 INT,

    PanelQtyWithHinge1 INT,
    PanelQtyWithHinge2 INT,
    PanelQtyWithHinge3 INT,
    PanelQtyWithHinge4 INT,
    PanelQtyWithHinge5 INT,
    PanelQtyWithHinge6 INT,

    LocationTPost1 INT,
    LocationTPost2 INT,
    LocationTPost3 INT,
    LocationTPost4 INT,
    LocationTPost5 INT,

    HorizontalTPost1 NVARCHAR(100),
    HorizontalTPost2 NVARCHAR(100),
    HorizontalTPost3 NVARCHAR(100),
    HorizontalTPost4 NVARCHAR(100),
    HorizontalTPost5 NVARCHAR(100),
    HorizontalTPost6 NVARCHAR(100),

    HorizontalTPostHeight1 INT,
    HorizontalTPostHeight2 INT,
    HorizontalTPostHeight3 INT,
    HorizontalTPostHeight4 INT,
    HorizontalTPostHeight5 INT,
    HorizontalTPostHeight6 INT,

    JoinedPanels1 NVARCHAR(100),
    JoinedPanels2 NVARCHAR(100),
    JoinedPanels3 NVARCHAR(100),
    JoinedPanels4 NVARCHAR(100),
    JoinedPanels5 NVARCHAR(100),
    JoinedPanels6 NVARCHAR(100),

    ReverseHinged1 NVARCHAR(100),
    ReverseHinged2 NVARCHAR(100),
    ReverseHinged3 NVARCHAR(100),
    ReverseHinged4 NVARCHAR(100),
    ReverseHinged5 NVARCHAR(100),
    ReverseHinged6 NVARCHAR(100),

    PelmetFlat1 NVARCHAR(100),
    PelmetFlat2 NVARCHAR(100),
    PelmetFlat3 NVARCHAR(100),
    PelmetFlat4 NVARCHAR(100),
    PelmetFlat5 NVARCHAR(100),
    PelmetFlat6 NVARCHAR(100),

    ExtraFascia1 NVARCHAR(100),
    ExtraFascia2 NVARCHAR(100),
    ExtraFascia3 NVARCHAR(100),
    ExtraFascia4 NVARCHAR(100),
    ExtraFascia5 NVARCHAR(100),
    ExtraFascia6 NVARCHAR(100),

    HingesLoose1 NVARCHAR(100),
    HingesLoose2 NVARCHAR(100),
    HingesLoose3 NVARCHAR(100),
    HingesLoose4 NVARCHAR(100),
    HingesLoose5 NVARCHAR(100),
    HingesLoose6 NVARCHAR(100),

    TiltrodType1 NVARCHAR(100),
    TiltrodType2 NVARCHAR(100),
    TiltrodType3 NVARCHAR(100),
    TiltrodType4 NVARCHAR(100),
    TiltrodType5 NVARCHAR(100),
    TiltrodType6 NVARCHAR(100),

    TiltrodSplit1 NVARCHAR(100),
    TiltrodSplit2 NVARCHAR(100),
    TiltrodSplit3 NVARCHAR(100),
    TiltrodSplit4 NVARCHAR(100),
    TiltrodSplit5 NVARCHAR(100),
    TiltrodSplit6 NVARCHAR(100),

    SplitHeight1 INT,
    SplitHeight2 INT,
    SplitHeight3 INT,
    SplitHeight4 INT,
    SplitHeight5 INT,
    SplitHeight6 INT,

    DoorCutOut1 NVARCHAR(100),
    DoorCutOut2 NVARCHAR(100),
    DoorCutOut3 NVARCHAR(100),
    DoorCutOut4 NVARCHAR(100),
    DoorCutOut5 NVARCHAR(100),
    DoorCutOut6 NVARCHAR(100),

    SpecialShape1 NVARCHAR(100),
    SpecialShape2 NVARCHAR(100),
    SpecialShape3 NVARCHAR(100),
    SpecialShape4 NVARCHAR(100),
    SpecialShape5 NVARCHAR(100),
    SpecialShape6 NVARCHAR(100),

    TemplateProvided1 NVARCHAR(100),
    TemplateProvided2 NVARCHAR(100),
    TemplateProvided3 NVARCHAR(100),
    TemplateProvided4 NVARCHAR(100),
    TemplateProvided5 NVARCHAR(100),
    TemplateProvided6 NVARCHAR(100),

    SquareMetre1 DECIMAL(18, 2),
    SquareMetre2 DECIMAL(18, 2),
    SquareMetre3 DECIMAL(18, 2),
    SquareMetre4 DECIMAL(18, 2),
    SquareMetre5 DECIMAL(18, 2),
    SquareMetre6 DECIMAL(18, 2),

    LinearMetre1 DECIMAL(18, 2),
    LinearMetre2 DECIMAL(18, 2),
    LinearMetre3 DECIMAL(18, 2),
    LinearMetre4 DECIMAL(18, 2),
    LinearMetre5 DECIMAL(18, 2),
    LinearMetre6 DECIMAL(18, 2),

    StackPosition1 NVARCHAR(100),
    StackPosition2 NVARCHAR(100),
    StackPosition3 NVARCHAR(100),
    StackPosition4 NVARCHAR(100),
    StackPosition5 NVARCHAR(100),
    StackPosition6 NVARCHAR(100),

    TilterPosition1 NVARCHAR(100),
    TilterPosition2 NVARCHAR(100),
    TilterPosition3 NVARCHAR(100),
    TilterPosition4 NVARCHAR(100),
    TilterPosition5 NVARCHAR(100),
    TilterPosition6 NVARCHAR(100),

    RollDirection1 NVARCHAR(100),
    RollDirection2 NVARCHAR(100),
    RollDirection3 NVARCHAR(100),
    RollDirection4 NVARCHAR(100),
    RollDirection5 NVARCHAR(100),
    RollDirection6 NVARCHAR(100),

    ControlPosition1 NVARCHAR(100),
    ControlPosition2 NVARCHAR(100),
    ControlPosition3 NVARCHAR(100),
    ControlPosition4 NVARCHAR(100),
    ControlPosition5 NVARCHAR(100),
    ControlPosition6 NVARCHAR(100),

    ControlColour1 NVARCHAR(100),
    ControlColour2 NVARCHAR(100),
    ControlColour3 NVARCHAR(100),
    ControlColour4 NVARCHAR(100),
    ControlColour5 NVARCHAR(100),
    ControlColour6 NVARCHAR(100),

    ControlLength1 INT,
    ControlLength2 INT,
    ControlLength3 INT,
    ControlLength4 INT,
    ControlLength5 INT,
    ControlLength6 INT,

    ChainLength1 INT,
    ChainLength2 INT,
    ChainLength3 INT,
    ChainLength4 INT,
    ChainLength5 INT,
    ChainLength6 INT,

    MaterialChain1 NVARCHAR(100),
    MaterialChain2 NVARCHAR(100),
    MaterialChain3 NVARCHAR(100),
    MaterialChain4 NVARCHAR(100),
    MaterialChain5 NVARCHAR(100),
    MaterialChain6 NVARCHAR(100),

    MotorStyle1 NVARCHAR(100),
    MotorStyle2 NVARCHAR(100),
    MotorStyle3 NVARCHAR(100),
    MotorStyle4 NVARCHAR(100),
    MotorStyle5 NVARCHAR(100),
    MotorStyle6 NVARCHAR(100),

    MotorRemote1 NVARCHAR(100),
    MotorRemote2 NVARCHAR(100),
    MotorRemote3 NVARCHAR(100),
    MotorRemote4 NVARCHAR(100),
    MotorRemote5 NVARCHAR(100),
    MotorRemote6 NVARCHAR(100),

    MotorRequired1 NVARCHAR(100),
    MotorRequired2 NVARCHAR(100),
    MotorRequired3 NVARCHAR(100),
    MotorRequired4 NVARCHAR(100),
    MotorRequired5 NVARCHAR(100),
    MotorRequired6 NVARCHAR(100),

    MotorBattery1 NVARCHAR(100),
    MotorBattery2 NVARCHAR(100),
    MotorBattery3 NVARCHAR(100),
    MotorBattery4 NVARCHAR(100),
    MotorBattery5 NVARCHAR(100),
    MotorBattery6 NVARCHAR(100),

    MotorCharger1 NVARCHAR(100),
    MotorCharger2 NVARCHAR(100),
    MotorCharger3 NVARCHAR(100),
    MotorCharger4 NVARCHAR(100),
    MotorCharger5 NVARCHAR(100),
    MotorCharger6 NVARCHAR(100),

    Connector1 NVARCHAR(100),
    Connector2 NVARCHAR(100),
    Connector3 NVARCHAR(100),
    Connector4 NVARCHAR(100),
    Connector5 NVARCHAR(100),
    Connector6 NVARCHAR(100),

    AdditionalMotor1 NVARCHAR(100),
    AdditionalMotor2 NVARCHAR(100),
    AdditionalMotor3 NVARCHAR(100),
    AdditionalMotor4 NVARCHAR(100),
    AdditionalMotor5 NVARCHAR(100),
    AdditionalMotor6 NVARCHAR(100),

    CableExitPoint1 NVARCHAR(100),
    CableExitPoint2 NVARCHAR(100),
    CableExitPoint3 NVARCHAR(100),
    CableExitPoint4 NVARCHAR(100),
    CableExitPoint5 NVARCHAR(100),
    CableExitPoint6 NVARCHAR(100),

    TrackType1 NVARCHAR(100),
    TrackType2 NVARCHAR(100),
    TrackType3 NVARCHAR(100),
    TrackType4 NVARCHAR(100),
    TrackType5 NVARCHAR(100),
    TrackType6 NVARCHAR(100),

    TrackColour1 NVARCHAR(100),
    TrackColour2 NVARCHAR(100),
    TrackColour3 NVARCHAR(100),
    TrackColour4 NVARCHAR(100),
    TrackColour5 NVARCHAR(100),
    TrackColour6 NVARCHAR(100),

    TrackLength1 INT,
    TrackLength2 INT,
    TrackLength3 INT,
    TrackLength4 INT,
    TrackLength5 INT,
    TrackLength6 INT,

    NumOfWand1 INT,
    NumOfWand2 INT,
    NumOfWand3 INT,
    NumOfWand4 INT,
    NumOfWand5 INT,
    NumOfWand6 INT,

    WandPosition1 NVARCHAR(100),
    WandPosition2 NVARCHAR(100),
    WandPosition3 NVARCHAR(100),
    WandPosition4 NVARCHAR(100),
    WandPosition5 NVARCHAR(100),
    WandPosition6 NVARCHAR(100),

    WandColour1 NVARCHAR(100),
    WandColour2 NVARCHAR(100),
    WandColour3 NVARCHAR(100),
    WandColour4 NVARCHAR(100),
    WandColour5 NVARCHAR(100),
    WandColour6 NVARCHAR(100),

    WandLength1 INT,
    WandLength2 INT,
    WandLength3 INT,
    WandLength4 INT,
    WandLength5 INT,
    WandLength6 INT,

    CordColour1 NVARCHAR(100),
    CordColour2 NVARCHAR(100),
    CordColour3 NVARCHAR(100),
    CordColour4 NVARCHAR(100),
    CordColour5 NVARCHAR(100),
    CordColour6 NVARCHAR(100),

    CordLength1 INT,
    CordLength2 INT,
    CordLength3 INT,
    CordLength4 INT,
    CordLength5 INT,
    CordLength6 INT,

    AcornPlasticColour1 NVARCHAR(100),
    AcornPlasticColour2 NVARCHAR(100),
    AcornPlasticColour3 NVARCHAR(100),
    AcornPlasticColour4 NVARCHAR(100),
    AcornPlasticColour5 NVARCHAR(100),
    AcornPlasticColour6 NVARCHAR(100),

    Accessory1 NVARCHAR(100),
    Accessory2 NVARCHAR(100),
    Accessory3 NVARCHAR(100),
    Accessory4 NVARCHAR(100),
    Accessory5 NVARCHAR(100),
    Accessory6 NVARCHAR(100),

    SideBySide1 NVARCHAR(100),
    SideBySide2 NVARCHAR(100),
    SideBySide3 NVARCHAR(100),
    SideBySide4 NVARCHAR(100),
    SideBySide5 NVARCHAR(100),
    SideBySide6 NVARCHAR(100),

    SlatSize1 NVARCHAR(100),
    SlatSize2 NVARCHAR(100),
    SlatSize3 NVARCHAR(100),
    SlatSize4 NVARCHAR(100),
    SlatSize5 NVARCHAR(100),
    SlatSize6 NVARCHAR(100),

    SlatQty1 INT,
    SlatQty2 INT,
    SlatQty3 INT,
    SlatQty4 INT,
    SlatQty5 INT,
    SlatQty6 INT,

    TubeSize1 NVARCHAR(100),
    TubeSize2 NVARCHAR(100),
    TubeSize3 NVARCHAR(100),
    TubeSize4 NVARCHAR(100),
    TubeSize5 NVARCHAR(100),
    TubeSize6 NVARCHAR(100),

    Trim1 NVARCHAR(100),
    Trim2 NVARCHAR(100),
    Trim3 NVARCHAR(100),
    Trim4 NVARCHAR(100),
    Trim5 NVARCHAR(100),
    Trim6 NVARCHAR(100),

    Batten1 NVARCHAR(100),
    Batten2 NVARCHAR(100),
    Batten3 NVARCHAR(100),
    Batten4 NVARCHAR(100),
    Batten5 NVARCHAR(100),
    Batten6 NVARCHAR(100),

    BattenColour1 NVARCHAR(100),
    BattenColour2 NVARCHAR(100),
    BattenColour3 NVARCHAR(100),
    BattenColour4 NVARCHAR(100),
    BattenColour5 NVARCHAR(100),
    BattenColour6 NVARCHAR(100),

    BracketOption1 NVARCHAR(100),
    BracketOption2 NVARCHAR(100),
    BracketOption3 NVARCHAR(100),
    BracketOption4 NVARCHAR(100),
    BracketOption5 NVARCHAR(100),
    BracketOption6 NVARCHAR(100),

    BracketColour1 NVARCHAR(100),
    BracketColour2 NVARCHAR(100),
    BracketColour3 NVARCHAR(100),
    BracketColour4 NVARCHAR(100),
    BracketColour5 NVARCHAR(100),
    BracketColour6 NVARCHAR(100),

    BracketCover1 NVARCHAR(100),
    BracketCover2 NVARCHAR(100),
    BracketCover3 NVARCHAR(100),
    BracketCover4 NVARCHAR(100),
    BracketCover5 NVARCHAR(100),
    BracketCover6 NVARCHAR(100),

    BracketExtension1 NVARCHAR(100),
    BracketExtension2 NVARCHAR(100),
    BracketExtension3 NVARCHAR(100),
    BracketExtension4 NVARCHAR(100),
    BracketExtension5 NVARCHAR(100),
    BracketExtension6 NVARCHAR(100),
    
    Fitting1 NVARCHAR(100),
    Fitting2 NVARCHAR(100),
    Fitting3 NVARCHAR(100),
    Fitting4 NVARCHAR(100),
    Fitting5 NVARCHAR(100),
    Fitting6 NVARCHAR(100),

    FlatType1 NVARCHAR(100),
    FlatType2 NVARCHAR(100),
    FlatType3 NVARCHAR(100),
    FlatType4 NVARCHAR(100),
    FlatType5 NVARCHAR(100),
    FlatType6 NVARCHAR(100),
    ChildSafe1 NVARCHAR(100),
    ChildSafe2 NVARCHAR(100),
    ChildSafe3 NVARCHAR(100),
    ChildSafe4 NVARCHAR(100),
    ChildSafe5 NVARCHAR(100),
    ChildSafe6 NVARCHAR(100),

    Cleat1 NVARCHAR(100),
    Cleat2 NVARCHAR(100),
    Cleat3 NVARCHAR(100),
    Cleat4 NVARCHAR(100),
    Cleat5 NVARCHAR(100),
    Cleat6 NVARCHAR(100),

    BottomHoldDown1 NVARCHAR(100),
    BottomHoldDown2 NVARCHAR(100),
    BottomHoldDown3 NVARCHAR(100),
    BottomHoldDown4 NVARCHAR(100),
    BottomHoldDown5 NVARCHAR(100),
    BottomHoldDown6 NVARCHAR(100),

    HangerType1 NVARCHAR(100),
    HangerType2 NVARCHAR(100),
    HangerType3 NVARCHAR(100),
    HangerType4 NVARCHAR(100),
    HangerType5 NVARCHAR(100),
    HangerType6 NVARCHAR(100),

    PelmetType1 NVARCHAR(100),
    PelmetType2 NVARCHAR(100),
    PelmetType3 NVARCHAR(100),
    PelmetType4 NVARCHAR(100),
    PelmetType5 NVARCHAR(100),
    PelmetType6 NVARCHAR(100),

    PelmetWidth1 INT,
    PelmetWidth2 INT,
    PelmetWidth3 INT,
    PelmetWidth4 INT,
    PelmetWidth5 INT,
    PelmetWidth6 INT,

    PelmetSize1 NVARCHAR(100),
    PelmetSize2 NVARCHAR(100),
    PelmetSize3 NVARCHAR(100),
    PelmetSize4 NVARCHAR(100),
    PelmetSize5 NVARCHAR(100),
    PelmetSize6 NVARCHAR(100),

    PelmetReturn1 NVARCHAR(100),
    PelmetReturn2 NVARCHAR(100),
    PelmetReturn3 NVARCHAR(100),
    PelmetReturn4 NVARCHAR(100),
    PelmetReturn5 NVARCHAR(100),
    PelmetReturn6 NVARCHAR(100),

    PelmetReturnPosition1 NVARCHAR(100),
    PelmetReturnPosition2 NVARCHAR(100),
    PelmetReturnPosition3 NVARCHAR(100),
    PelmetReturnPosition4 NVARCHAR(100),
    PelmetReturnPosition5 NVARCHAR(100),
    PelmetReturnPosition6 NVARCHAR(100),

    PelmetReturnSize1 INT,
    PelmetReturnSize2 INT,
    PelmetReturnSize3 INT,
    PelmetReturnSize4 INT,
    PelmetReturnSize5 INT,
    PelmetReturnSize6 INT,

    PelmetReturnSize21 INT,
    PelmetReturnSize22 INT,
    PelmetReturnSize23 INT,
    PelmetReturnSize24 INT,
    PelmetReturnSize25 INT,
    PelmetReturnSize26 INT,

    CutOut_LeftTop1 INT,
    CutOut_LeftTop2 INT,
    CutOut_LeftTop3 INT,
    CutOut_LeftTop4 INT,
    CutOut_LeftTop5 INT,
    CutOut_LeftTop6 INT,

    CutOut_RightTop1 INT,
    CutOut_RightTop2 INT,
    CutOut_RightTop3 INT,
    CutOut_RightTop4 INT,
    CutOut_RightTop5 INT,
    CutOut_RightTop6 INT,

    CutOut_LeftBottom1 INT,
    CutOut_LeftBottom2 INT,
    CutOut_LeftBottom3 INT,
    CutOut_LeftBottom4 INT,
    CutOut_LeftBottom5 INT,
    CutOut_LeftBottom6 INT,

    CutOut_RightBottom1 INT,
    CutOut_RightBottom2 INT,
    CutOut_RightBottom3 INT,
    CutOut_RightBottom4 INT,
    CutOut_RightBottom5 INT,
    CutOut_RightBottom6 INT,

    LHSWidth_Top1 INT,
    LHSWidth_Top2 INT,
    LHSWidth_Top3 INT,
    LHSWidth_Top4 INT,
    LHSWidth_Top5 INT,
    LHSWidth_Top6 INT,

    LHSHeight_Top1 INT,
    LHSHeight_Top2 INT,
    LHSHeight_Top3 INT,
    LHSHeight_Top4 INT,
    LHSHeight_Top5 INT,
    LHSHeight_Top6 INT,

    RHSWidth_Top1 INT,
    RHSWidth_Top2 INT,
    RHSWidth_Top3 INT,
    RHSWidth_Top4 INT,
    RHSWidth_Top5 INT,
    RHSWidth_Top6 INT,

    RHSHeight_Top1 INT,
    RHSHeight_Top2 INT,
    RHSHeight_Top3 INT,
    RHSHeight_Top4 INT,
    RHSHeight_Top5 INT,
    RHSHeight_Top6 INT,

    LHSWidth_Bottom1 INT,
    LHSWidth_Bottom2 INT,
    LHSWidth_Bottom3 INT,
    LHSWidth_Bottom4 INT,
    LHSWidth_Bottom5 INT,
    LHSWidth_Bottom6 INT,

    LHSHeight_Bottom1 INT,
    LHSHeight_Bottom2 INT,
    LHSHeight_Bottom3 INT,
    LHSHeight_Bottom4 INT,
    LHSHeight_Bottom5 INT,
    LHSHeight_Bottom6 INT,

    RHSWidth_Bottom1 INT,
    RHSWidth_Bottom2 INT,
    RHSWidth_Bottom3 INT,
    RHSWidth_Bottom4 INT,
    RHSWidth_Bottom5 INT,
    RHSWidth_Bottom6 INT,

    RHSHeight_Bottom1 INT,
    RHSHeight_Bottom2 INT,
    RHSHeight_Bottom3 INT,
    RHSHeight_Bottom4 INT,
    RHSHeight_Bottom5 INT,
    RHSHeight_Bottom6 INT,

    BlindSize1 INT,
    BlindSize2 INT,
    BlindSize3 INT,
    BlindSize4 INT,
    BlindSize5 INT,
    BlindSize6 INT,

    Sloper1 BIT,
    Sloper2 BIT,
    Sloper3 BIT,
    Sloper4 BIT,
    Sloper5 BIT,
    Sloper6 BIT,

    InsertInTrack1 BIT,
    InsertInTrack2 BIT,
    InsertInTrack3 BIT,
    InsertInTrack4 BIT,
    InsertInTrack5 BIT,
    InsertInTrack6 BIT,

    Notes1 NVARCHAR(200),
    Notes2 NVARCHAR(200),
    Notes3 NVARCHAR(200),
    Notes4 NVARCHAR(200),
    Notes5 NVARCHAR(200),
    Notes6 NVARCHAR(200),

    KitName1 NVARCHAR(100),
    KitName2 NVARCHAR(100),
    KitName3 NVARCHAR(100),
    KitName4 NVARCHAR(100),
    KitName5 NVARCHAR(100),
    KitName6 NVARCHAR(100),

    BracketType1 NVARCHAR(100),
    BracketType2 NVARCHAR(100),
    BracketType3 NVARCHAR(100),
    BracketType4 NVARCHAR(100),
    BracketType5 NVARCHAR(100),
    BracketType6 NVARCHAR(100),

    TubeType1 NVARCHAR(100),
    TubeType2 NVARCHAR(100),
    TubeType3 NVARCHAR(100),
    TubeType4 NVARCHAR(100),
    TubeType5 NVARCHAR(100),
    TubeType6 NVARCHAR(100),

    ControlType1 NVARCHAR(100),
    ControlType2 NVARCHAR(100),
    ControlType3 NVARCHAR(100),
    ControlType4 NVARCHAR(100),
    ControlType5 NVARCHAR(100),
    ControlType6 NVARCHAR(100),

    ColourType1 NVARCHAR(100),
    ColourType2 NVARCHAR(100),
    ColourType3 NVARCHAR(100),
    ColourType4 NVARCHAR(100),
    ColourType5 NVARCHAR(100),
    ColourType6 NVARCHAR(100),

    -- DesignName NVARCHAR(100),
    -- BlindName NVARCHAR(100),
    ChainName1 NVARCHAR(100),
    ChainName2 NVARCHAR(100),
    ChainName3 NVARCHAR(100),
    ChainName4 NVARCHAR(100),
    ChainName5 NVARCHAR(100),
    ChainName6 NVARCHAR(100),
    
    ChainColour1 NVARCHAR(100),
    ChainColour2 NVARCHAR(100),
    ChainColour3 NVARCHAR(100),
    ChainColour4 NVARCHAR(100),
    ChainColour5 NVARCHAR(100),
    ChainColour6 NVARCHAR(100),
    
    CLength1 NVARCHAR(100),
    CLength2 NVARCHAR(100),
    CLength3 NVARCHAR(100),
    CLength4 NVARCHAR(100),
    CLength5 NVARCHAR(100),
    CLength6 NVARCHAR(100),

    BottomName1 NVARCHAR(100),
    BottomName2 NVARCHAR(100),
    BottomName3 NVARCHAR(100),
    BottomName4 NVARCHAR(100),
    BottomName5 NVARCHAR(100),
    BottomName6 NVARCHAR(100),
    
    BottomType1 NVARCHAR(100),
    BottomType2 NVARCHAR(100),
    BottomType3 NVARCHAR(100),
    BottomType4 NVARCHAR(100),
    BottomType5 NVARCHAR(100),
    BottomType6 NVARCHAR(100),
    
    BottomColour1 NVARCHAR(100),
    BottomColour2 NVARCHAR(100),
    BottomColour3 NVARCHAR(100),
    BottomColour4 NVARCHAR(100),
    BottomColour5 NVARCHAR(100),
    BottomColour6 NVARCHAR(100),

    FabricName1 NVARCHAR(100),
    FabricName2 NVARCHAR(100),
    FabricName3 NVARCHAR(100),
    FabricName4 NVARCHAR(100),
    FabricName5 NVARCHAR(100),
    FabricName6 NVARCHAR(100),

    FabricType1 NVARCHAR(100),
    FabricType2 NVARCHAR(100),
    FabricType3 NVARCHAR(100),
    FabricType4 NVARCHAR(100),
    FabricType5 NVARCHAR(100),
    FabricType6 NVARCHAR(100),

    FabricColour1 NVARCHAR(100),
    FabricColour2 NVARCHAR(100),
    FabricColour3 NVARCHAR(100),
    FabricColour4 NVARCHAR(100),
    FabricColour5 NVARCHAR(100),
    FabricColour6 NVARCHAR(100),

    FabricWidth1 INT,
    FabricWidth2 INT,
    FabricWidth3 INT,
    FabricWidth4 INT,
    FabricWidth5 INT,
    FabricWidth6 INT,

    FabricGroups1 NVARCHAR(100),
    FabricGroups2 NVARCHAR(100),
    FabricGroups3 NVARCHAR(100),
    FabricGroups4 NVARCHAR(100),
    FabricGroups5 NVARCHAR(100),
    FabricGroups6 NVARCHAR(100),

    OrderDelivery1 NVARCHAR(100),
    OrderDelivery2 NVARCHAR(100),
    OrderDelivery3 NVARCHAR(100),
    OrderDelivery4 NVARCHAR(100),
    OrderDelivery5 NVARCHAR(100),
    OrderDelivery6 NVARCHAR(100),

    PriceGroupName1 NVARCHAR(100),
    PriceGroupName2 NVARCHAR(100),
    PriceGroupName3 NVARCHAR(100),
    PriceGroupName4 NVARCHAR(100),
    PriceGroupName5 NVARCHAR(100),
    PriceGroupName6 NVARCHAR(100)
);

-- -- Indexing
CREATE NONCLUSTERED INDEX IDX_JobSheets_Id ON JobSheets (Id);
CREATE NONCLUSTERED INDEX IDX_JobSheets_JobId ON JobSheets (JobId);
CREATE NONCLUSTERED INDEX IDX_JobSheets_JoNumber ON JobSheets (JoNumber);
CREATE NONCLUSTERED INDEX IDX_JobSheets_HeaderId ON JobSheets (HeaderId);
CREATE NONCLUSTERED INDEX IDX_JobSheets_DesignName ON JobSheets (DesignName);
CREATE NONCLUSTERED INDEX IDX_JobSheets_BlindName ON JobSheets (BlindName);
