CREATE TABLE JobDetails (
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	JobId INT NOT NULL,
	DetailId INT NOT NULL,
	DesignType nvarchar(50),
	BlindType nvarchar(50),
	Qty INT,
	FabricType nvarchar(50),
	FabricColour nvarchar(50),
	TubeSkinSize INT,
	NumBoldNuts INT,
	--||Motor||--
	MotorStyle nvarchar(100), --motor
	MotorRemote nvarchar(100), -- motor
	MotorCharger nvarchar(100), -- motor
	[Trim] nvarchar(50),
	RollDirection nvarchar(50),
	HardwareType nvarchar(50),
	HardwareColour nvarchar(50),
	ControlPosition nvarchar(50),
	ChainColour nvarchar(50),
	ChildSafe nvarchar(50),
	ControlType nvarchar(100),
	ControlLength nvarchar(50),
	TubeSize INT,
	BrailType nvarchar(50),
	BrailColour nvarchar(50),
	Accessories nvarchar(50),
	SpringAssist nvarchar(50),
	BracketType nvarchar(50),
	LinkBlinds nvarchar(50),
	BracketColour nvarchar(50),
	--|| Alumminium||
	BracketOption nvarchar(50),
	WandLength INT,
	CutOutLeftTop INT,
	CutOutRightTop INT,
	CutOutLeftBot INT,
	CutOutRightBot INT,
	LHSWidthTop INT,
	LHSHeightTop INT,
	RHSWidthTop INT,
	RHSHeightTop INT,
	LHSWidthBot INT,
	LHSHeightBot INT,
	RHSWidthBot INT,
	RHSHeightBot INT,
	BottomHoldDown nvarchar(100),
	--||Vertical||
	TrackColour nvarchar(50),
	SlatSize nvarchar(100),
	CarriesQty INT,
	SpacerSize INT,
	TrackOption nvarchar(50),
	StackPosition nvarchar(50),
	HangerType nvarchar(100),
	BottomColour nvarchar(100),
	LeftHandReturn nvarchar(100),
	RightHandReturn nvarchar(100),
	Sloper nvarchar(50),
	InsertInTrack nvarchar(50),
	FabricCutDrop INT,
	
	Width INT,
	[Drop] INT,
	SpringType nvarchar(50),
	Mounting nvarchar(50),
	Room nvarchar(50),
);
CREATE INDEX idx_JobId ON JobDetails (JobId);
CREATE INDEX idx_DetailId ON JobDetails (DetailId);